### PR TITLE
Created bluetooth module

### PR DESCRIPTION
**Pull request by mbvissers**
Created a very minimal Bluetooth module using `bluetoothctl`.

### CODE REVIEW

**Comment by x70b1** [comment]
What about [system-bluetooth-bluetoothctl](https://github.com/polybar/polybar-scripts/tree/master/polybar-scripts/system-bluetooth-bluetoothctl) ?

**Comment by mbvissers** [comment]
Hey,For me, that module didn’t work for some reason. So I made something that’s as minimal as possible to also fit my own needs. But I can understand if my module might be too redundant for polybar-scripts.Op 6 okt. 2022 om 17:11 heeft x70b1 ***@***.***> het volgende geschreven:﻿
What about system-bluetooth-bluetoothctl ?

**Comment by x70b1** [comment]
Yeah, I understand this. On the other hand it would be cool to know whats wrong with the script on your system.
Whats the output of `bluetoothctl --version` ?

**Comment by x70b1** [comment]
Check this: https://github.com/polybar/polybar-scripts/pull/394

To make your script working with an older version than 5.65 replace `devices Paired` with `paired-devices`.

**Comment by mbvissers** [comment]
I've changed all three `devices Paired` with `paired-devices`, but I get an error from line 4: `read: arg count`.

**Comment by x70b1** [comment]
Which shell do you use?
Can you run it with the `-x` option and paste the output here (`bash -x bluetooth.sh`)?

**Comment by x70b1** [comment]
I tried with zsh here, works also fine for me. 

Then you need `zsh -x ./system-bluetooth-bluetoothctl.sh`.
It generates a lot of output, so maybe you can spot the area where the error is.

**Comment by mbvissers** [comment]
zsh -x ./system-bluetooth-bluetoothctl.sh outputs:

I cannot spot any errors, but I'm not that good at shell programming

```+/etc/zsh/zshenv:15> [[ -z /home/martijn/.local/share/pnpm:/home/martijn/.nvm/versions/node/v12.22.12/bin:/home/martijn/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin || /home/martijn/.local/share/pnpm:/home/martijn/.nvm/versions/node/v12.22.12/bin:/home/martijn/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin == /bin:/usr/bin ]]
+./system-bluetooth-bluetoothctl.sh:54> case  (--toggle)
+./system-bluetooth-bluetoothctl.sh:54> case  (*)
+./system-bluetooth-bluetoothctl.sh:59> bluetooth_print
+bluetooth_print:1> read -r
+bluetooth_print:1> bluetoothctl
+bluetooth_print:2> systemctl is-active bluetooth.service
+bluetooth_print:2> [ active '=' active ']'
+bluetooth_print:3> printf '#1'
#1+bluetooth_print:5> devices_paired=+bluetooth_print:5> bluetoothctl paired-devices
+bluetooth_print:5> devices_paired=+bluetooth_print:5> grep Device
+bluetooth_print:5> devices_paired=+bluetooth_print:5> cut -d ' ' -f 2
+bluetooth_print:5> devices_paired=$'74:9E:AF:AC:6A:FC\n60:AB:D2:3D:C3:97' 
+bluetooth_print:7> counter=0 
+bluetooth_print:9> device=74:9E:AF:AC:6A:FC
60:AB:D2:3D:C3:97
+bluetooth_print:10> device_info=+bluetooth_print:10> bluetoothctl info $'74:9E:AF:AC:6A:FC\n60:AB:D2:3D:C3:97'
+bluetooth_print:10> device_info=$'Device 74:9E:AF:AC:6A:FC\n60:AB:D2:3D:C3:97 not available' 
+bluetooth_print:12> echo $'Device 74:9E:AF:AC:6A:FC\n60:AB:D2:3D:C3:97 not available'
+bluetooth_print:12> grep -q 'Connected: yes'
+bluetooth_print:25> printf '\n'

+bluetooth_print:1> read -r
+bluetooth_print:2> systemctl is-active bluetooth.service
+bluetooth_print:2> [ active '=' active ']'
+bluetooth_print:3> printf '#1'
#1+bluetooth_print:5> devices_paired=+bluetooth_print:5> bluetoothctl paired-devices
+bluetooth_print:5> devices_paired=+bluetooth_print:5> grep Device
+bluetooth_print:5> devices_paired=+bluetooth_print:5> cut -d ' ' -f 2
+bluetooth_print:5> devices_paired=$'74:9E:AF:AC:6A:FC\n60:AB:D2:3D:C3:97' 
+bluetooth_print:7> counter=0 
+bluetooth_print:9> device=74:9E:AF:AC:6A:FC
60:AB:D2:3D:C3:97
+bluetooth_print:10> device_info=+bluetooth_print:10> bluetoothctl info $'74:9E:AF:AC:6A:FC\n60:AB:D2:3D:C3:97'
+bluetooth_print:10> device_info=$'Device 74:9E:AF:AC:6A:FC\n60:AB:D2:3D:C3:97 not available' 
+bluetooth_print:12> echo $'Device 74:9E:AF:AC:6A:FC\n60:AB:D2:3D:C3:97 not available'
+bluetooth_print:12> grep -q 'Connected: yes'
+bluetooth_print:25> printf '\n'

+bluetooth_print:1> read -r
```

**Comment by x70b1** [comment]
No errors there. If you run your script in a terminal with zsh then there should be no errors. But they are still there?

You could also play around with start and stopping your `bluetooth.service`and `zsh -x ./system-bluetooth-bluetoothctl.sh --toggle` in a second terminal. Maybe you can find out when the error happen.

**Comment by mbvissers** [comment]
I will do so, thanks! If I encounter anything wrong in the code I will send a PR for a fix.
But what should we do with this PR? Otherwise, I'll just create a public repo for my minimal module

**Comment by x70b1** [comment]
I you want you can create an own repo for this. I would set a link on the main README to it.
Then we can close this PR.

**Comment by mbvissers** [comment]
Agreed, thanks for your time :)

**Comment by x70b1** [comment]
Done in 76ddc87d09bba756d05c39f524cd338d3cd66368.

**Pull request closed without merging**
