### PR TITLE
Add polystock - A stock ticker viewer for polybar

### PR DESCRIPTION
**Pull request by zack-ashen**
I wrote a simple python script that displays custom stock prices, the biggest gaining stock prices in a day, the biggest losing stock prices in a day, the top crypto in a day, or the most active stock price in a day.

### CODE REVIEW

**Comment by x70b1** [comment]
I would add your repo to the [link section](https://github.com/polybar/polybar-scripts#see-also-these-other-user-repositories)?

**Comment by zack-ashen** [comment]
I just added to link section. Sorry about that.

**Comment by x70b1** [comment]
No problem. :sunglasses: 
The question is, one or the other? A link at the section or the script in this repo?
In an own repo you are able to maintain your own code. As you already have it, I'd prefer that.

**Comment by zack-ashen** [comment]
Ok, I removed from the repo and kept the link. Just to confirm this is what you would prefer? If not I don't care I can remove the link and go back to the original with it as a script in the repo. Thanks.

**Comment by x70b1** [comment]
This looks perfect! :+1:

**Pull request merged**
