### PR TITLE
added salah-time script

### PR DESCRIPTION
**Pull request by robinsrk**

### CODE REVIEW

**Comment by dzshn** [comment]
Sorry if this is a bold statement, but what's with `checkDate.py`? Using pickle for storing what seems to be a dict isn't the most safe or appropiate - as the docs even point out:
> It is possible to construct malicious pickle data which will execute arbitrary code during unpickling. Never unpickle data that could have come from an untrusted source, or that could have been tampered with.

I would recommend using json for it..

**Comment by robinsrk** [comment]
> Sorry if this is a bold statement, but what's with `checkDate.py`? Using pickle for storing what seems to be a dict isn't the most safe or appropiate - as the docs even point out:
> 
> > It is possible to construct malicious pickle data which will execute arbitrary code during unpickling. Never unpickle data that could have come from an untrusted source, or that could have been tampered with.
> 
> I would recommend using json for it..

it is storing the data, so that if internet is not working, or not available, it won't call the api again until next day. So the point of using that file is to store data for one day, and next day check the api and store the data.

**Comment by robinsrk** [comment]
> Sorry if this is a bold statement, but what's with `checkDate.py`? Using pickle for storing what seems to be a dict isn't the most safe or appropiate - as the docs even point out:
> 
> > It is possible to construct malicious pickle data which will execute arbitrary code during unpickling. Never unpickle data that could have come from an untrusted source, or that could have been tampered with.
> 
> I would recommend using json for it..

Ok I will push new updates soon with json formatted data

**Comment by x70b1** [comment]
Thanks for this PR!

I only see a limited use case here for other users. But if you want to setup an own reposiItory for this project, I would add it to the repo list on the main README.md.

**Pull request closed without merging**
