### PR TITLE
add gitlab pipelines module

### PR DESCRIPTION
**Pull request by FalcoSuessgott**
Displays the number of succeeded, running and failed gitlab-pipelines triggered by a user.

### CODE REVIEW

**Comment by x70b1** [comment]
Thanks for your PR!

Does this `time=$(date -d "$HOURS_AGO" --iso-8601=seconds)` really work?
I got a time at `6 am` but that is not a duration of 6 hours?

**Comment by FalcoSuessgott** [comment]
Hi @x70b1 ,

your right, it does seem weird although it worked on my laptop somehow.
Anyways, I found this command:

```
$date -d "6 hours ago" -Iseconds                                                                                                                    
2020-05-05T07:47:47+02:00
```

This should work better. Can submit a PullRequest

**Comment by x70b1** [comment]
Yes, looks better.
At the moment I don't have running GitLab here. What format does the Request expect as the argument value?

**Comment by FalcoSuessgott** [comment]
[https://docs.gitlab.com/ee/api/pipelines.html#list-project-pipelines](https://docs.gitlab.com/ee/api/pipelines.html#list-project-pipelines)

**See:**
updated_after | datetime | no | Return pipelines updated after the specified date. Format: ISO 8601 YYYY-MM-DDTHH:MM:SSZ
-- | -- | -- | --

**Comment by x70b1** [comment]
Ah nice. 
Yes, lets fix it in a PR :+1:

**Pull request merged**
