### PR TITLE
info-softwarecounter: the whole script has been refactored

### PR DESCRIPTION
**Pull request by jfernandz**
I have some improvments for this script I like very much. 

I hope you appreciate them. :wink:

BR and happy new year :blush:

### CODE REVIEW

**Comment by x70b1** [comment]
Awesome!
Is issue https://github.com/polybar/polybar-scripts/issues/314 also fixed then?

**Comment by jfernandz** [comment]
hmmm, no, apparently it's not solved, but I didn't know about that issue, I'm also realizeing I could also include support for telegram :thinking: or spotify ...

I think I'll work on these :wink:

**Comment by x70b1** [comment]
I looked into that issue some time ago but was not able to find the reason there. 
So if you would find a reason and a fix for this it would be very cool!

**Comment by jfernandz** [comment]
Sure I'm checking it :wink:

**Comment by jfernandz** [comment]
I'd say right know should work also for `urxvt` and `nautilus` :wink:

**Comment by jfernandz** [comment]
I'm still trying to improve a few things about new logging feature. I'll tell you when it's done :blush:

**Pull request merged**
