### PR TITLE
DualShock 4 Battery level

### PR DESCRIPTION
**Pull request by d3rrial**
This script shows the current battery level of the DualShock 4 Controller in 10% increments.
I'm not good with Bash, so someone please check if I forgot to escape something important or did something silly.

### CODE REVIEW

**Comment by x70b1** [comment]
Good idea!
Can you post an output of `/sys/class/power_supply/sony_controller_battery_*/capacity` ?
So that i can improve the script a bit.

**Comment by d3rrial** [comment]
The output is literally just an integer between 0 and 100
I'm not sure if I can describe it in any more meaningful way, sorry

**Comment by x70b1** [comment]
No thats enough! :)

**Comment by x70b1** [comment]
@d3rrial Thanks for the scripts!

**Pull request merged**
