### PR TITLE
openweathermap-fullfeatured.sh: curl -sf missing double quotes

### PR DESCRIPTION
**Pull request by FromWau**

### CODE REVIEW

**Comment by x70b1** [comment]
Why do you assume the quotes are required here?

**Comment by FromWau** [comment]
> Thanks for this! Why do you assume the quotes are required here?
Hi, 
curl fails for me without the quotes.

**Comment by x70b1** [comment]
This is interesting. I have no problems with it. Which shell do you use?

**Comment by FromWau** [comment]
> This is interesting. I have no problems with it. Which shell do you use?

I am using zsh and apparently does zsh (and fish) treat the `?` in the URL as a wildcard. 

`zsh -c 'curl -sf https://location.services.mozilla.com/v1/geolocate?key=geoclue'`
will cause: `zsh:1: no matches found: https://location.services.mozilla.com/v1/geolocate?key=geoclue`
Escaping the `?` via `\` or by adding quotes resolves it.

**Comment by x70b1** [comment]
Perfect! I merged your PR. 
Thanks for your work!

**Pull request closed without merging**
