### PR TITLE
system-fan-speed: fix empty speed

### PR DESCRIPTION
**Pull request by muntjaber**
Fix issue with speed expression returning empty string instead of integer.

### CODE REVIEW

**Review by x70b1 — COMMENTED** [review]
Sorry for the delay. 

I guess it would also a good idea to use the condition in line 5. 
Does something like  `if [ -n "$speed" ]; then` work?

**Comment by muntjaber** [comment]
Yes, that is required. If `fan1` doesn't exist, an empty string will be returned which results in a syntax error when evaluating `speed_round`.

**Comment by x70b1** [comment]
Yes. But is a real problem?

Are threre cases where your system rename a fan?

**Comment by muntjaber** [comment]
No, not that I am aware of. However, using the current solution, it failed to identify the field using a count of 9 spaces (returning an empty string). Hence, the proposed changed: delimit by any number of spaces instead, and select the second field.

**Review by x70b1 — APPROVED** [review]

**Comment by x70b1** [comment]
Thx! :sunglasses:

**Pull request merged**
