### PR TITLE
Added pavolume module

### PR DESCRIPTION
**Pull request by marioortizmanero**
I've just added a very handy pavolume module. It looks simple but it's super useful, check the README for more.

### CODE REVIEW

**Comment by x70b1** [comment]
What is the real benefit over [pulseaudio-tail](https://github.com/polybar/polybar-scripts/tree/master/polybar-scripts/pulseaudio-tail) or polybars [pulseaudio module](https://github.com/polybar/polybar/wiki/Module:-pulseaudio)?

**Comment by marioortizmanero** [comment]
Well this script can switch between sinks very easily (and with a blacklist), which is why started this in the beginning. Without it you'd have to open pavucontrol, go to output devices, change the default one, go to audio sources, move all of them to the new device... Or do it with pacmd which is even worse.

It also has support for osd on kde, a volume cap and a couple other things

**Comment by juansquintero** [comment]
It works perfectly

**Comment by marioortizmanero** [comment]
So, have you considered adding it? Maybe I should put it in a repo of my own and add a link in the README instead?

**Comment by x70b1** [comment]
I would prefer to extend the existing script instead of adding a new one.
A separate repository would make sense. But thanks a lot for your contribution to polybar-scripts.

**Comment by marioortizmanero** [comment]
No problem! I've added the link to the repo in case you want to add it but you can just close the PR otherwise.

**Pull request merged**
