### PR TITLE
Add keyring (un)locker

### PR DESCRIPTION
**Pull request by IvoLeist**
Hey polybar users

first of all thank you for maintaining this awesome collection of polybar examples.
I already took many of these for my setup so now it is time for me to give something back.
And since we are in Barcelona in a "lockdown" situation at the moment...

Let me know if you are interested in that module so I can clean up the code/
make the naming more consistent that it fits in your collection.

Best,
Ivo

### CODE REVIEW

**Comment by x70b1** [comment]
Do you know the [pam-gnupg](https://github.com/cruegge/pam-gnupg) project?
You could combine this with a `pam` screenlocker and unlock your `pass`.

**Comment by IvoLeist** [comment]
Hello x70b1

thank you for your opinion.

yes on my search for a good solution I stumbled above the pam-gnupg project.
But I somehow did not managed to preset the passphrase.
Whichever settings I did pass kept asking me for the pass phrase
although I have seen in the gpg keylist that the pass phrase is cached.

gnome-keyring on the other hand enables me to skip the pass phrase
prompt as long the keyring is unlocked.

Additionally I am reluctant to unlock my keyring with my login password thats
why I use the gnome-keyring with another password.

I might be a little paranoid but since my Laptop is at the moment my 
only computer and thus password store for everything I just want to be on the safe side

Don't you think that  gnome-keyring "workaround" is a good solution?
Why would you prefer pam?

**Comment by x70b1** [comment]
Thats just my point of view. 

I use a PAM-based screenlocker to unlock everything. My `pass` with `pam-gnupg` and my ssh keys with [pam_exec-ssh](https://github.com/x70b1/pam_exec-ssh). I run the screenlocker at the boot of my system without a display manager. So that I unlock all the stuff on my first login. 

Its lightweight and you can configure everything in files.

I used the gnome-keyring too. But for me I wanted a smaller solution. Its not bad or unsafe. But the keyring-daemon, seahorse and dbus-requirement was to much for me.

**Comment by x70b1** [comment]
Should we still work on this script?

**Comment by IvoLeist** [comment]
@x70b1 depends if you like my gnome-keyring solution?
Right now I do not have the time to look deeper into pam_exec

**Comment by x70b1** [comment]
Well, you have a number of scripts here in this PR. That makes it a bit difficult.
So I close it. 

But I am happy that you have found a solution for you.  :+1:

**Pull request closed without merging**
