### PR TITLE
vpn-networkmanager-status: VPN status command for NetworkManager/nmcli

### PR DESCRIPTION
**Pull request by sn0wvall**
When trying to use the vpn-openvpn-status script, I got simply got the message "nm-openvpn" - probably more a limitation of NetworkManager than the script. Therefore, I put together this script which will output the active NetworkManager-started VPN.

### CODE REVIEW

**Comment by x70b1** [comment]
Just for understanding, does it not work with [network-networkmanager](https://github.com/polybar/polybar-scripts/tree/master/polybar-scripts/network-networkmanager)?
I guess we would have to add a new `network type`? This would give you the benefit of realtime updates.

**Comment by sn0wvall** [comment]
The scripts are similar, however this script is more minimal providing only the VPN connection name, and excluding the redundant "tun0" from the output of network-networkmanager.

**Comment by x70b1** [comment]
Nice work, thx!

**Comment by x70b1** [comment]
I rewrote some parts. Maybe you want to check it: https://github.com/polybar/polybar-scripts/commit/0424be6f4c11a31cb56044239f52ab4fac7365bb

**Pull request merged**
