### PR TITLE
redshift-control : Added scripts & readme

### PR DESCRIPTION
**Pull request by VineshReddy**
Change, display temperature and on/off redshift.

### CODE REVIEW

**Comment by VineshReddy** [comment]
Hey , build failed because of a shell file with environment variables

**Comment by x70b1** [comment]
We have already a script for redshift: [info-redshift-temp ](https://github.com/polybar/polybar-scripts/tree/master/polybar-scripts/info-redshift-temp)
It would be better if we improve this instead of creating a new one. The only things that needs to be added are the actions.

**Comment by VineshReddy** [comment]
Yes thats fine, Can this repo be added [polybar-redshift](https://github.com/VineshReddy/polybar-redshift) to other user repositories. Thank you.
I can PR for it.

**Comment by x70b1** [comment]
Just open a PR for that.

**Pull request closed without merging**
